name: Prettify Code

on: [push, pull_request]

jobs:
  prettify:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Add this line to grant write permissions

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Prettify code
      run: npx prettier -w .

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'chore: auto-format code'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
